# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6dcdc3f6bd1ed89ace0d0c2ed869a3e13962dd897a03851d539e55bb75c959b58f817251b342c42afdacf5e7f443e5559d3490fd3acc33faad88f6be60f2bbd

test:
  secret_key_base: 2b0eb0329e38aa1dd8576b4964f0e794cad82300ac9de6d7af75db2d5da1351dae950b82fabd678ace482fa8fc631fb49c44bc3abfcdf53ccc589dc4e85d73ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
